#!/usr/bin/env bash

set -ex

.circleci/setup_git

PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH

yarn global add @oclif/semantic-release@3 semantic-release@15
yarn install --frozen-lockfile
semantic-release -e @oclif/semantic-release
