#!/usr/bin/env bash

set -ex

duration() {
  set +x
  start=$(date +%s)
  "$@"
  end=$(date +%s)
  python -c "print 'Ran $1 in %u:%02u' % ((${end} - ${start})/60, (${end} - ${start})%60)"
  set -x
}

PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH

if [[ ! -z "$GIT_EMAIL" ]] & [[ ! -z "$GIT_USERNAME" ]]; then
  git config --global push.default simple
  git config --global user.email "$GIT_EMAIL"
  git config --global user.user "$GIT_USERNAME"
fi

_test() {
  CLI_ENGINE_UTIL_YARN_ARGS="--frozen-lockfile"

  if [[ "$CIRCLE_BRANCH" == greenkeeper/* ]]; then
    CLI_ENGINE_GREENKEEPER_BRANCH=1
    CLI_ENGINE_UTIL_YARN_ARGS=""
    if [[ ! -x "$(command -v greenkeeper-lockfile-update)" ]]; then
      duration yarn global add greenkeeper-lockfile@1
    fi
    duration greenkeeper-lockfile-update
  fi

  duration yarn install $CLI_ENGINE_UTIL_YARN_ARGS

  if [[ "$CLI_ENGINE_GREENKEEPER_BRANCH" == 1 ]]; then
    duration greenkeeper-lockfile-upload
  fi

  CWD=$(pwd)
  NYC=(./node_modules/.bin/nyc --nycrc-path node_modules/@dxcli/dev-nyc-config/.nycrc)
  mkdir -p reports
  MOCHA_FILE="$CWD/reports/mocha.xml" \
    DXCLI_MOCHA_OPTS="--reporter mocha-junit-reporter" \
    DXCLI_ESLINT_OPTS="--format junit --output-file $CWD/reports/eslint.xml" \
    DXCLI_TSLINT_OPTS="--format junit > $CWD/reports/tslint.xml" \
    duration "${NYC[@]}" yarn test

  duration "${NYC[@]}" report --reporter=text-lcov > coverage.lcov

  duration curl -s https://codecov.io/bash | bash
}

_release() {
  yarn --frozen-lockfile
  ./node_modules/.bin/dxcli-dev-semantic-release
}

case "$1" in
  release) _release;;
  *) _test;;
esac
